### ISSUE TITLE
Data issue with Franco Colapinto

### ISSUE THREAD

**Issue by joseywoermann** [ssyyhhrr/stewardle#10]
Guessing Franco Colapinto doesn't "work". Multiple values are missing, and the comparisons to other drivers don't seem to get color coded at all.
This is a genuine problem, because Colapinto would be the solution to today's (07. 09. 2024) stewardle, but the game doesn't recognize this.

I assume this issue is happening because Franco Colapinto's driver number hasn't been added to the database which the API uses yet.
With Ergast shutting down soon #8, I don't know if this issue will be corrected, maybe stewardle should switch to the new API #9  soon.

![Screenshot_20240907_091935_Firefox](https://github.com/user-attachments/assets/7e991979-0005-4bf2-946b-69e6cce6b569)

**Comment by ssyyhhrr** [comment]
Thanks for raising this issue, because there were previously no Argentinian drivers in the game, I hadn't added the mapping for the nationality to the flag file, which then destroyed the rest of the formatting.

I have added mappings for Argentinian, among other nationalities in https://github.com/ssyyhhrr/stewardle/commit/b48dfdca670e58921b943e26933075c10bce7ad2 to prevent this issue occurring again.
